import { HttpStatus } from '@nestjs/common';

import type { ErrorCodeKey } from './error-codes';

export const DOMAIN_HTTP_MAP: Record<ErrorCodeKey, number> = {
  CATEGORY_NOT_FOUND: HttpStatus.NOT_FOUND,
  CATEGORY_NAME_TAKEN: HttpStatus.CONFLICT,
  CATEGORY_BELONGS_TO_OTHER_USER: HttpStatus.FORBIDDEN,
  CANNOT_DELETE_DEFAULT_CATEGORY: HttpStatus.CONFLICT,
  ACCOUNT_NOT_FOUND: HttpStatus.NOT_FOUND,
  ACCOUNT_NAME_TAKEN: HttpStatus.CONFLICT,
  ACCOUNT_HAS_ACTIVE_TRANSACTIONS: HttpStatus.CONFLICT,
  ACCOUNT_BELONGS_TO_OTHER_USER: HttpStatus.FORBIDDEN,
  CANNOT_CHANGE_CURRENCY_WITH_TX: HttpStatus.CONFLICT,
  USER_NOT_FOUND: HttpStatus.NOT_FOUND,
  USER_INACTIVE: HttpStatus.FORBIDDEN,
  INVALID_REFRESH_TOKEN: HttpStatus.UNAUTHORIZED,
  INVALID_MONEY_AMOUNT: HttpStatus.UNPROCESSABLE_ENTITY,
  CURRENCY_MISMATCH: HttpStatus.UNPROCESSABLE_ENTITY,
  VALIDATION_ERROR: HttpStatus.BAD_REQUEST,
};
