export const ERROR_CODES = {
  // Categories
  CATEGORY_NOT_FOUND: 'CAT_001',
  CATEGORY_NAME_TAKEN: 'CAT_002',
  CATEGORY_BELONGS_TO_OTHER_USER: 'CAT_003',
  CANNOT_DELETE_DEFAULT_CATEGORY: 'CAT_004',
  // Accounts
  ACCOUNT_NOT_FOUND: 'ACC_001',
  ACCOUNT_NAME_TAKEN: 'ACC_002',
  ACCOUNT_HAS_ACTIVE_TRANSACTIONS: 'ACC_003',
  ACCOUNT_BELONGS_TO_OTHER_USER: 'ACC_004',
  CANNOT_CHANGE_CURRENCY_WITH_TX: 'ACC_005',
  // Users
  USER_NOT_FOUND: 'USR_001',
  USER_INACTIVE: 'USR_002',
  // Auth
  INVALID_REFRESH_TOKEN: 'AUT_001',
  // Domain value objects
  INVALID_MONEY_AMOUNT: 'VAL_001',
  CURRENCY_MISMATCH: 'VAL_002',
  // Transactions
  TRANSACTION_NOT_FOUND: 'TXN_001',
  TRANSACTION_BELONGS_TO_OTHER_USER: 'TXN_002',
  INSUFFICIENT_BALANCE: 'TXN_003',
  TRANSFER_SAME_ACCOUNT: 'TXN_004',
  TRANSFER_CURRENCY_MISMATCH: 'TXN_005',
  DESTINATION_ACCOUNT_NOT_FOUND: 'TXN_006',
  TRANSFER_DESTINATION_REQUIRED: 'TXN_007',
  REFERENCE_REQUIRED: 'TXN_008',
  TRANSACTION_NOT_DEBT_OR_LOAN: 'TXN_009',
  TRANSACTION_ALREADY_SETTLED: 'TXN_010',
  CANNOT_UPDATE_SETTLED_TRANSACTION: 'TXN_011',
  SETTLEMENT_AMOUNT_EXCEEDS_REMAINING: 'TXN_012',
  // Validation
  VALIDATION_ERROR: 'GEN_001',
} as const;

export type ErrorCodeKey = keyof typeof ERROR_CODES;
