import { type MigrationInterface, type QueryRunner } from 'typeorm';

/**
 * Slice 2 of the `shared-service-payments` feature. Adds
 * `sourceMonthlyServicePaymentId` to `debts_loans` — the link that lets a
 * `LOAN` row generated by a shared monthly-service payment be traced back
 * to the payment that created it (used to gather `linkedDebts[]` on the
 * service response and to cascade soft-delete on payment revert).
 *
 * Schema decisions:
 *
 *  - Nullable `uuid` column, NO FK constraint — same decoupled-FK
 *    convention as `debts_loans.categoryId` (migration `1741000028000`).
 *    A hard FK to `monthly_service_payments` would couple the delete
 *    order between two independently-owned modules for no real
 *    referential-integrity benefit here: the app enforces the link (the
 *    delete-payment use case explicitly soft-deletes unsettled linked
 *    debts before finishing), and payments are soft-deleted, not hard
 *    -deleted, so a real FK would never even fire an ON DELETE CASCADE
 *    for the normal revert flow.
 *
 *  - Plain (non-unique, non-partial) index on the column — the only read
 *    pattern is `findBySourcePaymentIds(ids)` (an IN-list lookup), no
 *    need for a composite or partial index.
 *
 *  - No backfill: pre-existing `debts_loans` rows (created manually, not
 *    via a shared-service payment) get `NULL`, which is the correct
 *    "not linked to any payment" state.
 */
export class AddSourcePaymentToDebtsLoans1741000038000 implements MigrationInterface {
  name = 'AddSourcePaymentToDebtsLoans1741000038000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "debts_loans"
        ADD COLUMN "sourceMonthlyServicePaymentId" uuid NULL
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_debts_loans_source_payment"
        ON "debts_loans" ("sourceMonthlyServicePaymentId")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_debts_loans_source_payment"`);
    await queryRunner.query(
      `ALTER TABLE "debts_loans" DROP COLUMN IF EXISTS "sourceMonthlyServicePaymentId"`,
    );
  }
}
