import { Injectable } from '@nestjs/common';

import { DebtLoanRepository } from '@modules/debts-loans/domain/debt-loan.repository';
import { DebtLoanStatus } from '@modules/debts-loans/domain/enums/debt-loan-status.enum';
import { MonthlyServicePaymentRepository } from '@modules/monthly-service-payments/domain/monthly-service-payment.repository';

/** One entry in `MonthlyServiceResponseDto.linkedDebts`. */
export interface LinkedDebtSummary {
  id: string;
  reference: string;
  remainingAmount: number;
  status: 'PENDING';
}

/**
 * Gathers the PENDING `LOAN`s generated by a shared monthly-service's
 * payments (shared-service-payments slice 2). Shared between
 * `GetMonthlyServiceUseCase` and `ListMonthlyServicesUseCase` — per
 * CLAUDE.md rule #8 (no single-use helpers, 2+ callers → shared unit) —
 * both need the exact same gather-and-map logic for the
 * `linkedDebts[]` response field.
 *
 * SETTLED linked debts are intentionally excluded — they remain visible
 * as history in `GET /debts` but no longer need action from the
 * Services view (settling is done once, from either view — single
 * source of truth per the design's cross-view settle requirement).
 */
@Injectable()
export class LinkedDebtsGatherer {
  constructor(
    private readonly paymentRepo: MonthlyServicePaymentRepository,
    private readonly debtLoanRepo: DebtLoanRepository,
  ) {}

  async forService(monthlyServiceId: string): Promise<LinkedDebtSummary[]> {
    const payments = await this.paymentRepo.findByServiceId(monthlyServiceId);
    if (payments.length === 0) return [];

    const debts = await this.debtLoanRepo.findBySourcePaymentIds(payments.map((p) => p.id));

    return debts
      .filter((d) => d.status === DebtLoanStatus.PENDING)
      .map((d) => ({
        id: d.id,
        reference: d.reference,
        remainingAmount: d.remainingAmount,
        status: 'PENDING' as const,
      }));
  }
}
